export const galleryCategories = [
  "All",
  "SFW",
  "NSFW",
  "Goth",
  "Vacation",
  "Instagram",
  "TikTok",
  "Cosplay",
  "Luxury",
  "Selfie / UGC",
  "Gym",
  "Exercise",
  "Lingerie",
  "Swimwear",
  "Lifestyle",
  "Influencer",
  "Anime",
  "Sci-Fi",
  "Cars",
  "Motorcycles",
] as const;

export type GalleryCategory = (typeof galleryCategories)[number];
export type GalleryAudience = "individual" | "agency" | "brand";
export type GalleryVertical = "adult" | "non-adult" | "general";
export type GalleryType = "image" | "video";

export type GalleryItem = {
  src: string;
  title: string;
  category: Exclude<GalleryCategory, "All" | "SFW" | "NSFW">;
  audience: GalleryAudience[];
  vertical: GalleryVertical;
  type: GalleryType;
  nsfw: boolean;
  description: string;
};

export const galleryItems: GalleryItem[] = [
  {
    src: "/gallery/goth/goth-01.jpg",
    title: "Dark Goth Look",
    category: "Goth",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Alternative styling with dramatic makeup and darker mood.",
  },
  {
    src: "/gallery/vacation/vacation-01.jpg",
    title: "Vacation Lifestyle",
    category: "Vacation",
    audience: ["individual", "agency"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Travel-ready vacation visuals with polished destination mood.",
  },
  {
    src: "/gallery/instagram/instagram-01.jpg",
    title: "Instagram Premium Feed",
    category: "Instagram",
    audience: ["individual", "agency"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "High-engagement visual style tailored for Instagram output.",
  },
  {
    src: "/gallery/tiktok/tiktok-01.mp4",
    title: "Short-Form Social Vibe",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "video",
    nsfw: false,
    description: "Vertical short-form look optimized for dance and fast social cuts.",
  },
  {
    src: "/gallery/cosplay/cosplay-01.jpg",
    title: "Cosplay Character Session",
    category: "Cosplay",
    audience: ["individual", "agency"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Character-themed style control for fandom and niche aesthetics.",
  },
  {
    src: "/gallery/luxury/luxury-01.jpg",
    title: "Luxury Glam Editorial",
    category: "Luxury",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "High-end glam look with polished, premium framing.",
  },
  {
    src: "/gallery/selfie/selfie-01.jpg",
    title: "Selfie / UGC Natural",
    category: "Selfie / UGC",
    audience: ["individual", "agency"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "UGC-friendly aesthetic with natural tone and platform realism.",
  },
  {
    src: "/gallery/gym/gym-01.jpg",
    title: "Gym Content Generation",
    category: "Gym",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Athletic gym visuals for fitness creators and wellness brands.",
  },
  {
    src: "/gallery/exercise/exercise-01.jpg",
    title: "Exercise Activewear Flow",
    category: "Exercise",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Action-ready activewear scenes and movement-focused compositions.",
  },
  {
    src: "/gallery/lingerie/lingerie-01.jpg",
    title: "Lingerie Mood Set",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Premium lingerie style with mood-driven lighting control.",
  },
  {
    src: "/gallery/swimwear/swimwear-01.jpg",
    title: "Swimwear Beach Style",
    category: "Swimwear",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: true,
    description: "Beach and poolside swimwear outputs from soft to bold aesthetics.",
  },
  {
    src: "/gallery/lifestyle/lifestyle-01.jpg",
    title: "Lifestyle Daily Scene",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle look for broad creator and brand positioning.",
  },
  {
    src: "/gallery/influencer/influencer-01.jpg",
    title: "Influencer Signature Look",
    category: "Influencer",
    audience: ["individual", "agency"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Signature personal-brand aesthetics for modern influencer content.",
  },
  {
    src: "/gallery/anime/anime-01.jpg",
    title: "Anime-Inspired Visual",
    category: "Anime",
    audience: ["individual", "agency"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Anime-inspired style adaptation while retaining creator identity.",
  },
  {
    src: "/gallery/scifi/scifi-01.jpg",
    title: "Sci-Fi Futuristic Set",
    category: "Sci-Fi",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Futuristic lighting, wardrobe, and cinematic scene control.",
  },
  {
    src: "/gallery/cars/cars-01.jpg",
    title: "Automotive Visual Style",
    category: "Cars",
    audience: ["agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Automotive and car-focused content generation for non-adult verticals.",
  },
  {
    src: "/gallery/motorcycles/motorcycles-01.jpg",
    title: "Motorcycle Edge Aesthetic",
    category: "Motorcycles",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Motorcycle-focused style and mood with bold visual identity.",
  },
  {
    src: "/gallery/nsfw/nsfw-01.jpg",
    title: "Premium Adult Style",
    category: "Influencer",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented premium style example with configurable mood.",
  },
];

export const homeGalleryPreviewItems: GalleryItem[] = [
  galleryItems[0],
  galleryItems[2],
  galleryItems[3],
  galleryItems[7],
  galleryItems[9],
  galleryItems[12],
  galleryItems[15],
  galleryItems[16],
];
