export const galleryCategories = [
  "All",
  "SFW",
  "NSFW",
  "Goth",
  "Vacation",
  "Instagram",
  "TikTok",
  "Cosplay",
  "Luxury",
  "Selfie / UGC",
  "Gym",
  "Exercise",
  "Lingerie",
  "Swimwear",
  "Lifestyle",
  "Influencer",
  "Anime",
  "Sci-Fi",
  "Cars",
  "Motorcycles",
] as const;

export type GalleryCategory = (typeof galleryCategories)[number];
export type GalleryAudience = "individual" | "agency" | "brand";
export type GalleryVertical = "adult" | "non-adult" | "general";
export type GalleryType = "image" | "video";

export type GalleryItem = {
  src: string;
  title: string;
  category: Exclude<GalleryCategory, "All">;
  audience: GalleryAudience[];
  vertical: GalleryVertical;
  type: GalleryType;
  nsfw: boolean;
  description: string;
};

export const galleryItems: GalleryItem[] = [
  {
    src: "/gallery/sfw/photo_2026-01-13_03-29-38 (2).jpg",
    title: "Photo 2026 01 13 03 29 38 (2)",
    category: "SFW",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Safe-for-work style example for broad creator and brand output.",
  },
  {
    src: "/gallery/sfw/photo_2026-01-13_03-29-38 (3).jpg",
    title: "Photo 2026 01 13 03 29 38 (3)",
    category: "SFW",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Safe-for-work style example for broad creator and brand output.",
  },
  {
    src: "/gallery/sfw/photo_2026-01-13_03-29-38 (4).jpg",
    title: "Photo 2026 01 13 03 29 38 (4)",
    category: "SFW",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Safe-for-work style example for broad creator and brand output.",
  },
  {
    src: "/gallery/sfw/photo_2026-01-13_03-29-38.jpg",
    title: "Photo 2026 01 13 03 29 38",
    category: "SFW",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Safe-for-work style example for broad creator and brand output.",
  },
  {
    src: "/gallery/sfw/photo_2026-03-04_14-01-06.jpg",
    title: "Photo 2026 03 04 14 01 06",
    category: "SFW",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Safe-for-work style example for broad creator and brand output.",
  },
  {
    src: "/gallery/nsfw/ComfyUI_00070_.mp4",
    title: "Comfyui 00070",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "video",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/Wanimate_00004-audio.mp4",
    title: "Wanimate 00004 Audio",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "video",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/ai-clothes-changer-1.jpg",
    title: "Ai Clothes Changer 1",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/counting clothses.mp4",
    title: "Counting Clothses",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "video",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-01-24_15-52-25 (2).jpg",
    title: "Photo 2025 01 24 15 52 25 (2)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-01-24_15-52-26 (2).jpg",
    title: "Photo 2025 01 24 15 52 26 (2)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-01-24_15-52-26.jpg",
    title: "Photo 2025 01 24 15 52 26",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-01-24_15-52-27 (2).jpg",
    title: "Photo 2025 01 24 15 52 27 (2)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-01-27_22-38-11 (3).jpg",
    title: "Photo 2025 01 27 22 38 11 (3)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-01-27_22-38-11.jpg",
    title: "Photo 2025 01 27 22 38 11",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-01-29_06-48-28.jpg",
    title: "Photo 2025 01 29 06 48 28",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-04-21_15-36-23 (2).jpg",
    title: "Photo 2025 04 21 15 36 23 (2)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-04-21_15-36-23.jpg",
    title: "Photo 2025 04 21 15 36 23",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-04-21_15-36-25.jpg",
    title: "Photo 2025 04 21 15 36 25",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-06-28_09-23-45 (2).jpg",
    title: "Photo 2025 06 28 09 23 45 (2)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-06-28_09-23-45.jpg",
    title: "Photo 2025 06 28 09 23 45",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-06-28_09-23-46.jpg",
    title: "Photo 2025 06 28 09 23 46",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-06-28_09-23-47.jpg",
    title: "Photo 2025 06 28 09 23 47",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-08-10_13-30-08 (2).jpg",
    title: "Photo 2025 08 10 13 30 08 (2)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-08-10_13-30-08.jpg",
    title: "Photo 2025 08 10 13 30 08",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-08-10_13-30-09.jpg",
    title: "Photo 2025 08 10 13 30 09",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-08-15_10-38-21.jpg",
    title: "Photo 2025 08 15 10 38 21",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-08-16_17-35-13.jpg",
    title: "Photo 2025 08 16 17 35 13",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-08-17_18-01-19 (2).jpg",
    title: "Photo 2025 08 17 18 01 19 (2)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-08-17_18-01-19.jpg",
    title: "Photo 2025 08 17 18 01 19",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-08-18_03-14-25.jpg",
    title: "Photo 2025 08 18 03 14 25",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-08-18_21-11-39.jpg",
    title: "Photo 2025 08 18 21 11 39",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-08-20_16-53-42 (2).jpg",
    title: "Photo 2025 08 20 16 53 42 (2)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-08-20_16-53-45 (2).jpg",
    title: "Photo 2025 08 20 16 53 45 (2)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-03_07-58-49 (2).jpg",
    title: "Photo 2025 09 03 07 58 49 (2)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-03_07-58-49.jpg",
    title: "Photo 2025 09 03 07 58 49",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-07_22-23-02.jpg",
    title: "Photo 2025 09 07 22 23 02",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-07_22-25-02.jpg",
    title: "Photo 2025 09 07 22 25 02",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-22_23-49-48 (2).jpg",
    title: "Photo 2025 09 22 23 49 48 (2)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-22_23-49-48 (5).jpg",
    title: "Photo 2025 09 22 23 49 48 (5)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-22_23-49-48 (6).jpg",
    title: "Photo 2025 09 22 23 49 48 (6)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-22_23-49-49 (3).jpg",
    title: "Photo 2025 09 22 23 49 49 (3)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-22_23-49-49 (5).jpg",
    title: "Photo 2025 09 22 23 49 49 (5)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-22_23-49-49 (6).jpg",
    title: "Photo 2025 09 22 23 49 49 (6)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-22_23-49-50 (2).jpg",
    title: "Photo 2025 09 22 23 49 50 (2)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-22_23-49-50 (4).jpg",
    title: "Photo 2025 09 22 23 49 50 (4)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-22_23-49-51.jpg",
    title: "Photo 2025 09 22 23 49 51",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-30_08-29-22 (2).jpg",
    title: "Photo 2025 09 30 08 29 22 (2)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-30_08-29-22.jpg",
    title: "Photo 2025 09 30 08 29 22",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-30_09-01-54.jpg",
    title: "Photo 2025 09 30 09 01 54",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-30_09-01-55 (2).jpg",
    title: "Photo 2025 09 30 09 01 55 (2)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-30_09-01-56 (2).jpg",
    title: "Photo 2025 09 30 09 01 56 (2)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-30_09-01-56.jpg",
    title: "Photo 2025 09 30 09 01 56",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-10-01_10-04-13.jpg",
    title: "Photo 2025 10 01 10 04 13",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-10-01_21-07-08.jpg",
    title: "Photo 2025 10 01 21 07 08",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-10-01_21-07-39 (2).jpg",
    title: "Photo 2025 10 01 21 07 39 (2)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-10-01_21-07-39.jpg",
    title: "Photo 2025 10 01 21 07 39",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-10-01_21-07-41.jpg",
    title: "Photo 2025 10 01 21 07 41",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-10-01_21-07-59.jpg",
    title: "Photo 2025 10 01 21 07 59",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-10-01_22-02-02 (2).jpg",
    title: "Photo 2025 10 01 22 02 02 (2)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-10-01_22-02-02.jpg",
    title: "Photo 2025 10 01 22 02 02",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-10-01_22-02-03.jpg",
    title: "Photo 2025 10 01 22 02 03",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-10-01_22-02-06.jpg",
    title: "Photo 2025 10 01 22 02 06",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-10-01_22-02-07 (2).jpg",
    title: "Photo 2025 10 01 22 02 07 (2)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-10-01_22-02-07.jpg",
    title: "Photo 2025 10 01 22 02 07",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-10-17_17-25-31.jpg",
    title: "Photo 2025 10 17 17 25 31",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-01_13-38-15 (2).jpg",
    title: "Photo 2025 11 01 13 38 15 (2)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-01_13-38-15.jpg",
    title: "Photo 2025 11 01 13 38 15",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-02_05-58-10 (2).jpg",
    title: "Photo 2025 11 02 05 58 10 (2)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-02_05-58-10 (3).jpg",
    title: "Photo 2025 11 02 05 58 10 (3)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-02_05-58-10 (4).jpg",
    title: "Photo 2025 11 02 05 58 10 (4)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-02_05-58-10.jpg",
    title: "Photo 2025 11 02 05 58 10",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-02_05-58-24 (2).jpg",
    title: "Photo 2025 11 02 05 58 24 (2)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-02_05-58-24 (3).jpg",
    title: "Photo 2025 11 02 05 58 24 (3)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-02_05-58-24 (4).jpg",
    title: "Photo 2025 11 02 05 58 24 (4)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-02_05-58-24.jpg",
    title: "Photo 2025 11 02 05 58 24",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-02_05-58-34 (2).jpg",
    title: "Photo 2025 11 02 05 58 34 (2)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-02_05-58-46 (2).jpg",
    title: "Photo 2025 11 02 05 58 46 (2)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-02_05-58-46 (5).jpg",
    title: "Photo 2025 11 02 05 58 46 (5)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-05_20-23-59 (2).jpg",
    title: "Photo 2025 11 05 20 23 59 (2)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-05_20-23-59.jpg",
    title: "Photo 2025 11 05 20 23 59",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-11_06-33-29 (2).jpg",
    title: "Photo 2025 11 11 06 33 29 (2)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-11_06-33-29.jpg",
    title: "Photo 2025 11 11 06 33 29",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-24_11-58-31.jpg",
    title: "Photo 2025 11 24 11 58 31",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2026-01-03_10-03-09 (2).jpg",
    title: "Photo 2026 01 03 10 03 09 (2)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2026-01-03_10-03-09.jpg",
    title: "Photo 2026 01 03 10 03 09",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2026-01-15_05-43-31.jpg",
    title: "Photo 2026 01 15 05 43 31",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2026-02-07_20-34-15 (2).jpg",
    title: "Photo 2026 02 07 20 34 15 (2)",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2026-02-24_15-12-52.jpg",
    title: "Photo 2026 02 24 15 12 52",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2026-02-24_15-18-21.jpg",
    title: "Photo 2026 02 24 15 18 21",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2026-03-04_14-01-40.jpg",
    title: "Photo 2026 03 04 14 01 40",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2026-03-04_14-01-41.jpg",
    title: "Photo 2026 03 04 14 01 41",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/goth/0223.mp4",
    title: "0223",
    category: "Goth",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "video",
    nsfw: false,
    description: "Alternative dark aesthetic with goth styling and mood control.",
  },
  {
    src: "/gallery/goth/photo_2025-06-27_07-56-07.jpg",
    title: "Photo 2025 06 27 07 56 07",
    category: "Goth",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Alternative dark aesthetic with goth styling and mood control.",
  },
  {
    src: "/gallery/goth/photo_2025-07-14_10-57-44.jpg",
    title: "Photo 2025 07 14 10 57 44",
    category: "Goth",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Alternative dark aesthetic with goth styling and mood control.",
  },
  {
    src: "/gallery/goth/photo_2025-09-30_09-01-54 (2).jpg",
    title: "Photo 2025 09 30 09 01 54 (2)",
    category: "Goth",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Alternative dark aesthetic with goth styling and mood control.",
  },
  {
    src: "/gallery/goth/photo_2025-09-30_09-01-55.jpg",
    title: "Photo 2025 09 30 09 01 55",
    category: "Goth",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Alternative dark aesthetic with goth styling and mood control.",
  },
  {
    src: "/gallery/instagram/photo_2025-01-27_22-38-11 (2).jpg",
    title: "Photo 2025 01 27 22 38 11 (2)",
    category: "Instagram",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Instagram-ready polished aesthetic for premium social feeds.",
  },
  {
    src: "/gallery/instagram/photo_2025-01-27_22-38-12.jpg",
    title: "Photo 2025 01 27 22 38 12",
    category: "Instagram",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Instagram-ready polished aesthetic for premium social feeds.",
  },
  {
    src: "/gallery/instagram/photo_2026-03-04_14-00-47.jpg",
    title: "Photo 2026 03 04 14 00 47",
    category: "Instagram",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Instagram-ready polished aesthetic for premium social feeds.",
  },
  {
    src: "/gallery/tiktok/0210 (1).mp4",
    title: "0210 (1)",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "video",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/0219.mp4",
    title: "0219",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "video",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/0224.mp4",
    title: "0224",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "video",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/1008(2).mp4",
    title: "1008(2)",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "video",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/ComfyUI_00018_.mp4",
    title: "Comfyui 00018",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "video",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/Onlytwinvideo2.mp4",
    title: "Onlytwinvideo2",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "video",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/Wanimate_00005-audio.mp4",
    title: "Wanimate 00005 Audio",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "video",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/ai-clothes-changer-2.jpg",
    title: "Ai Clothes Changer 2",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/ai-clothes-changer-4.jpg",
    title: "Ai Clothes Changer 4",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/kling_20251007_Image_to_Video_the_woman__5943_0.mp4",
    title: "Kling 20251007 Image To Video The Woman 5943 0",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "video",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2025-01-27_22-38-11 (4).jpg",
    title: "Photo 2025 01 27 22 38 11 (4)",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2025-07-15_20-48-03.jpg",
    title: "Photo 2025 07 15 20 48 03",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2025-09-30_09-01-55 (3).jpg",
    title: "Photo 2025 09 30 09 01 55 (3)",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2025-10-02_10-40-32.jpg",
    title: "Photo 2025 10 02 10 40 32",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2025-10-02_10-46-33 (2).jpg",
    title: "Photo 2025 10 02 10 46 33 (2)",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2025-10-02_10-46-33.jpg",
    title: "Photo 2025 10 02 10 46 33",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2025-10-03_05-57-05 (2).jpg",
    title: "Photo 2025 10 03 05 57 05 (2)",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2025-10-03_05-57-05.jpg",
    title: "Photo 2025 10 03 05 57 05",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2025-10-26_06-51-41.jpg",
    title: "Photo 2025 10 26 06 51 41",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2025-11-02_05-58-34 (3).jpg",
    title: "Photo 2025 11 02 05 58 34 (3)",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2025-11-02_05-58-34.jpg",
    title: "Photo 2025 11 02 05 58 34",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2025-11-02_05-58-46 (4).jpg",
    title: "Photo 2025 11 02 05 58 46 (4)",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2025-11-02_05-58-46.jpg",
    title: "Photo 2025 11 02 05 58 46",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2025-11-17_01-15-07 (2).jpg",
    title: "Photo 2025 11 17 01 15 07 (2)",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2025-11-17_01-15-07.jpg",
    title: "Photo 2025 11 17 01 15 07",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-01-11_18-40-46.jpg",
    title: "Photo 2026 01 11 18 40 46",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-01-11_19-06-54.jpg",
    title: "Photo 2026 01 11 19 06 54",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-01-11_19-07-02.jpg",
    title: "Photo 2026 01 11 19 07 02",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-01-13_03-34-50 (2).jpg",
    title: "Photo 2026 01 13 03 34 50 (2)",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-01-13_03-34-50.jpg",
    title: "Photo 2026 01 13 03 34 50",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-02-07_20-32-37 (2).jpg",
    title: "Photo 2026 02 07 20 32 37 (2)",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-02-07_20-33-56 (3).jpg",
    title: "Photo 2026 02 07 20 33 56 (3)",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-02-07_20-33-56.jpg",
    title: "Photo 2026 02 07 20 33 56",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-02-07_20-33-57.jpg",
    title: "Photo 2026 02 07 20 33 57",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-02-07_20-33-59.jpg",
    title: "Photo 2026 02 07 20 33 59",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-02-07_20-34-07.jpg",
    title: "Photo 2026 02 07 20 34 07",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-02-24_15-18-16.jpg",
    title: "Photo 2026 02 24 15 18 16",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-02-24_15-18-17.jpg",
    title: "Photo 2026 02 24 15 18 17",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-02-24_15-18-20.jpg",
    title: "Photo 2026 02 24 15 18 20",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-00-26.jpg",
    title: "Photo 2026 03 04 14 00 26",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-00-28.jpg",
    title: "Photo 2026 03 04 14 00 28",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-00-33.jpg",
    title: "Photo 2026 03 04 14 00 33",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-00-35.jpg",
    title: "Photo 2026 03 04 14 00 35",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-00-46.jpg",
    title: "Photo 2026 03 04 14 00 46",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-00-56.jpg",
    title: "Photo 2026 03 04 14 00 56",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-01-01 (2).jpg",
    title: "Photo 2026 03 04 14 01 01 (2)",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-01-01.jpg",
    title: "Photo 2026 03 04 14 01 01",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-01-09.jpg",
    title: "Photo 2026 03 04 14 01 09",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-01-20 (2).jpg",
    title: "Photo 2026 03 04 14 01 20 (2)",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-01-20.jpg",
    title: "Photo 2026 03 04 14 01 20",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-01-22.jpg",
    title: "Photo 2026 03 04 14 01 22",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-01-38.jpg",
    title: "Photo 2026 03 04 14 01 38",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-01-44.jpg",
    title: "Photo 2026 03 04 14 01 44",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-01-46.jpg",
    title: "Photo 2026 03 04 14 01 46",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-01-49.jpg",
    title: "Photo 2026 03 04 14 01 49",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-01-53.jpg",
    title: "Photo 2026 03 04 14 01 53",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-02-02 (2).jpg",
    title: "Photo 2026 03 04 14 02 02 (2)",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-02-02.jpg",
    title: "Photo 2026 03 04 14 02 02",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-02-04.jpg",
    title: "Photo 2026 03 04 14 02 04",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/cosplay/photo_2025-08-20_16-53-34.jpg",
    title: "Photo 2025 08 20 16 53 34",
    category: "Cosplay",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Character and cosplay-focused generation with niche styling.",
  },
  {
    src: "/gallery/cosplay/photo_2025-08-20_16-53-44.jpg",
    title: "Photo 2025 08 20 16 53 44",
    category: "Cosplay",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Character and cosplay-focused generation with niche styling.",
  },
  {
    src: "/gallery/luxury/photo_2025-08-20_16-53-43.jpg",
    title: "Photo 2025 08 20 16 53 43",
    category: "Luxury",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Luxury and glam visual direction with premium editorial polish.",
  },
  {
    src: "/gallery/luxury/photo_2025-08-22_07-22-12 (2).jpg",
    title: "Photo 2025 08 22 07 22 12 (2)",
    category: "Luxury",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Luxury and glam visual direction with premium editorial polish.",
  },
  {
    src: "/gallery/luxury/photo_2026-02-07_20-34-15.jpg",
    title: "Photo 2026 02 07 20 34 15",
    category: "Luxury",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Luxury and glam visual direction with premium editorial polish.",
  },
  {
    src: "/gallery/selfie/photo_2025-09-22_23-49-48 (4).jpg",
    title: "Photo 2025 09 22 23 49 48 (4)",
    category: "Selfie / UGC",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "UGC-style selfie output designed for natural platform realism.",
  },
  {
    src: "/gallery/selfie/photo_2025-09-22_23-49-48 (7).jpg",
    title: "Photo 2025 09 22 23 49 48 (7)",
    category: "Selfie / UGC",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "UGC-style selfie output designed for natural platform realism.",
  },
  {
    src: "/gallery/selfie/photo_2025-09-22_23-49-48 (9).jpg",
    title: "Photo 2025 09 22 23 49 48 (9)",
    category: "Selfie / UGC",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "UGC-style selfie output designed for natural platform realism.",
  },
  {
    src: "/gallery/selfie/photo_2025-09-22_23-49-48.jpg",
    title: "Photo 2025 09 22 23 49 48",
    category: "Selfie / UGC",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "UGC-style selfie output designed for natural platform realism.",
  },
  {
    src: "/gallery/selfie/photo_2025-10-01_21-07-08 (3).jpg",
    title: "Photo 2025 10 01 21 07 08 (3)",
    category: "Selfie / UGC",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "UGC-style selfie output designed for natural platform realism.",
  },
  {
    src: "/gallery/selfie/photo_2026-03-04_14-01-52.jpg",
    title: "Photo 2026 03 04 14 01 52",
    category: "Selfie / UGC",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "UGC-style selfie output designed for natural platform realism.",
  },
  {
    src: "/gallery/gym/photo_2026-03-04_14-00-39.jpg",
    title: "Photo 2026 03 04 14 00 39",
    category: "Gym",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Fitness and gym style generation for workout and training niches.",
  },
  {
    src: "/gallery/exercise/photo_2025-01-29_06-48-24.jpg",
    title: "Photo 2025 01 29 06 48 24",
    category: "Exercise",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Exercise and activewear-focused visuals with motion-driven styling.",
  },
  {
    src: "/gallery/exercise/photo_2026-02-07_20-32-37.jpg",
    title: "Photo 2026 02 07 20 32 37",
    category: "Exercise",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Exercise and activewear-focused visuals with motion-driven styling.",
  },
  {
    src: "/gallery/exercise/photo_2026-02-24_15-18-23.jpg",
    title: "Photo 2026 02 24 15 18 23",
    category: "Exercise",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Exercise and activewear-focused visuals with motion-driven styling.",
  },
  {
    src: "/gallery/exercise/photo_2026-02-24_15-18-26.jpg",
    title: "Photo 2026 02 24 15 18 26",
    category: "Exercise",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Exercise and activewear-focused visuals with motion-driven styling.",
  },
  {
    src: "/gallery/exercise/photo_2026-03-04_14-00-43.jpg",
    title: "Photo 2026 03 04 14 00 43",
    category: "Exercise",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Exercise and activewear-focused visuals with motion-driven styling.",
  },
  {
    src: "/gallery/exercise/photo_2026-03-04_14-00-55.jpg",
    title: "Photo 2026 03 04 14 00 55",
    category: "Exercise",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Exercise and activewear-focused visuals with motion-driven styling.",
  },
  {
    src: "/gallery/exercise/photo_2026-03-04_14-00-57.jpg",
    title: "Photo 2026 03 04 14 00 57",
    category: "Exercise",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Exercise and activewear-focused visuals with motion-driven styling.",
  },
  {
    src: "/gallery/exercise/photo_2026-03-04_14-00-58.jpg",
    title: "Photo 2026 03 04 14 00 58",
    category: "Exercise",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Exercise and activewear-focused visuals with motion-driven styling.",
  },
  {
    src: "/gallery/lingerie/photo_2025-01-24_15-52-24.jpg",
    title: "Photo 2025 01 24 15 52 24",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2025-01-24_15-52-25.jpg",
    title: "Photo 2025 01 24 15 52 25",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2025-01-24_15-52-27.jpg",
    title: "Photo 2025 01 24 15 52 27",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2025-01-27_22-38-10.jpg",
    title: "Photo 2025 01 27 22 38 10",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2025-01-27_22-38-12 (2).jpg",
    title: "Photo 2025 01 27 22 38 12 (2)",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2025-08-18_21-11-12 (2).jpg",
    title: "Photo 2025 08 18 21 11 12 (2)",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2025-08-18_21-11-12.jpg",
    title: "Photo 2025 08 18 21 11 12",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2025-08-18_21-12-03 (2).jpg",
    title: "Photo 2025 08 18 21 12 03 (2)",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2025-09-04_20-22-16.jpg",
    title: "Photo 2025 09 04 20 22 16",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2025-09-22_23-49-49 (2).jpg",
    title: "Photo 2025 09 22 23 49 49 (2)",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2025-09-22_23-49-49 (4).jpg",
    title: "Photo 2025 09 22 23 49 49 (4)",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2025-09-22_23-49-49.jpg",
    title: "Photo 2025 09 22 23 49 49",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2025-09-22_23-49-50 (3).jpg",
    title: "Photo 2025 09 22 23 49 50 (3)",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2025-10-01_21-07-08 (2).jpg",
    title: "Photo 2025 10 01 21 07 08 (2)",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2026-02-07_20-33-55 (2).jpg",
    title: "Photo 2026 02 07 20 33 55 (2)",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2026-02-07_20-34-00.jpg",
    title: "Photo 2026 02 07 20 34 00",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2026-02-24_15-12-53.jpg",
    title: "Photo 2026 02 24 15 12 53",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2026-03-04_14-01-22 (2).jpg",
    title: "Photo 2026 03 04 14 01 22 (2)",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2026-03-04_14-01-24.jpg",
    title: "Photo 2026 03 04 14 01 24",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2026-03-04_14-01-25.jpg",
    title: "Photo 2026 03 04 14 01 25",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2026-03-04_14-01-27 (2).jpg",
    title: "Photo 2026 03 04 14 01 27 (2)",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2026-03-04_14-01-27.jpg",
    title: "Photo 2026 03 04 14 01 27",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2026-03-04_14-02-00.jpg",
    title: "Photo 2026 03 04 14 02 00",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2026-03-04_14-02-01.jpg",
    title: "Photo 2026 03 04 14 02 01",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/swimwear/photo_2025-07-23_17-23-44.jpg",
    title: "Photo 2025 07 23 17 23 44",
    category: "Swimwear",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Swimwear and beach-oriented visuals across social and promo use.",
  },
  {
    src: "/gallery/swimwear/photo_2025-11-02_05-58-46 (3).jpg",
    title: "Photo 2025 11 02 05 58 46 (3)",
    category: "Swimwear",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Swimwear and beach-oriented visuals across social and promo use.",
  },
  {
    src: "/gallery/swimwear/photo_2026-02-07_20-34-05.jpg",
    title: "Photo 2026 02 07 20 34 05",
    category: "Swimwear",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Swimwear and beach-oriented visuals across social and promo use.",
  },
  {
    src: "/gallery/swimwear/photo_2026-02-07_20-34-06.jpg",
    title: "Photo 2026 02 07 20 34 06",
    category: "Swimwear",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Swimwear and beach-oriented visuals across social and promo use.",
  },
  {
    src: "/gallery/lifestyle/photo_2025-04-21_15-36-24.jpg",
    title: "Photo 2025 04 21 15 36 24",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2025-07-03_16-54-23.jpg",
    title: "Photo 2025 07 03 16 54 23",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2025-08-18_21-11-13.jpg",
    title: "Photo 2025 08 18 21 11 13",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2025-08-18_21-12-03.jpg",
    title: "Photo 2025 08 18 21 12 03",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2025-08-22_07-22-12.jpg",
    title: "Photo 2025 08 22 07 22 12",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2025-09-22_23-49-48 (3).jpg",
    title: "Photo 2025 09 22 23 49 48 (3)",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2025-09-22_23-49-48 (8).jpg",
    title: "Photo 2025 09 22 23 49 48 (8)",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2025-09-22_23-49-50 (5).jpg",
    title: "Photo 2025 09 22 23 49 50 (5)",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2025-09-22_23-49-50.jpg",
    title: "Photo 2025 09 22 23 49 50",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2025-09-27_04-36-10 (4).jpg",
    title: "Photo 2025 09 27 04 36 10 (4)",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2025-09-27_04-36-10.jpg",
    title: "Photo 2025 09 27 04 36 10",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2025-10-01_10-04-13 (2).jpg",
    title: "Photo 2025 10 01 10 04 13 (2)",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2025-11-05_20-26-34 (2).jpg",
    title: "Photo 2025 11 05 20 26 34 (2)",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2025-11-05_20-26-34.jpg",
    title: "Photo 2025 11 05 20 26 34",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2026-01-11_18-46-57.jpg",
    title: "Photo 2026 01 11 18 46 57",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2026-01-13_03-42-37 (2).jpg",
    title: "Photo 2026 01 13 03 42 37 (2)",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2026-01-13_03-42-37.jpg",
    title: "Photo 2026 01 13 03 42 37",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2026-02-07_20-32-38.jpg",
    title: "Photo 2026 02 07 20 32 38",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2026-02-07_20-33-56 (2).jpg",
    title: "Photo 2026 02 07 20 33 56 (2)",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2026-02-07_20-34-05 (2).jpg",
    title: "Photo 2026 02 07 20 34 05 (2)",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2026-02-07_20-34-07 (2).jpg",
    title: "Photo 2026 02 07 20 34 07 (2)",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2026-02-07_20-34-07 (3).jpg",
    title: "Photo 2026 02 07 20 34 07 (3)",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2026-02-24_15-18-27.jpg",
    title: "Photo 2026 02 24 15 18 27",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2026-02-24_15-18-28.jpg",
    title: "Photo 2026 02 24 15 18 28",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2026-02-24_15-18-30.jpg",
    title: "Photo 2026 02 24 15 18 30",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2026-03-04_14-00-34.jpg",
    title: "Photo 2026 03 04 14 00 34",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2026-03-04_14-00-36.jpg",
    title: "Photo 2026 03 04 14 00 36",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2026-03-04_14-00-49.jpg",
    title: "Photo 2026 03 04 14 00 49",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2026-03-04_14-01-15.jpg",
    title: "Photo 2026 03 04 14 01 15",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2026-03-04_14-01-34.jpg",
    title: "Photo 2026 03 04 14 01 34",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2026-03-04_14-01-42.jpg",
    title: "Photo 2026 03 04 14 01 42",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/influencer/ai-clothes-changer-3.jpg",
    title: "Ai Clothes Changer 3",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/influencer/photo_2025-08-20_16-53-34 (2).jpg",
    title: "Photo 2025 08 20 16 53 34 (2)",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/influencer/photo_2025-08-20_16-53-43 (2).jpg",
    title: "Photo 2025 08 20 16 53 43 (2)",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/influencer/photo_2025-08-20_16-53-45.jpg",
    title: "Photo 2025 08 20 16 53 45",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/influencer/photo_2025-09-27_04-36-10 (3).jpg",
    title: "Photo 2025 09 27 04 36 10 (3)",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/influencer/photo_2025-09-27_04-36-11.jpg",
    title: "Photo 2025 09 27 04 36 11",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/influencer/photo_2025-10-04_10-49-36.jpg",
    title: "Photo 2025 10 04 10 49 36",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/influencer/photo_2025-10-04_18-18-22 (2).jpg",
    title: "Photo 2025 10 04 18 18 22 (2)",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/influencer/photo_2025-10-04_18-18-22.jpg",
    title: "Photo 2025 10 04 18 18 22",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/influencer/photo_2025-10-04_18-22-52.jpg",
    title: "Photo 2025 10 04 18 22 52",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/influencer/photo_2025-11-17_21-26-13 (2).jpg",
    title: "Photo 2025 11 17 21 26 13 (2)",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/influencer/photo_2026-02-07_20-33-55.jpg",
    title: "Photo 2026 02 07 20 33 55",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/influencer/photo_2026-02-07_20-33-58 (2).jpg",
    title: "Photo 2026 02 07 20 33 58 (2)",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/influencer/photo_2026-02-07_20-33-58.jpg",
    title: "Photo 2026 02 07 20 33 58",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/influencer/photo_2026-02-07_20-34-01.jpg",
    title: "Photo 2026 02 07 20 34 01",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/influencer/photo_2026-03-04_14-00-50.jpg",
    title: "Photo 2026 03 04 14 00 50",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/influencer/photo_2026-03-04_14-01-36.jpg",
    title: "Photo 2026 03 04 14 01 36",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/influencer/photo_2026-03-04_14-01-47.jpg",
    title: "Photo 2026 03 04 14 01 47",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/scifi/photo_2025-08-20_16-53-42.jpg",
    title: "Photo 2025 08 20 16 53 42",
    category: "Sci-Fi",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Sci-fi and futuristic looks with cinematic lighting and scenes.",
  },
  {
    src: "/gallery/scifi/photo_2025-11-17_21-26-13.jpg",
    title: "Photo 2025 11 17 21 26 13",
    category: "Sci-Fi",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Sci-fi and futuristic looks with cinematic lighting and scenes.",
  },
  {
    src: "/gallery/cars/photo_2025-09-27_04-36-10 (2).jpg",
    title: "Photo 2025 09 27 04 36 10 (2)",
    category: "Cars",
    audience: ["agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Automotive content style for car-focused creator and brand campaigns.",
  },
  {
    src: "/gallery/cars/photo_2025-09-27_04-36-10 (5).jpg",
    title: "Photo 2025 09 27 04 36 10 (5)",
    category: "Cars",
    audience: ["agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Automotive content style for car-focused creator and brand campaigns.",
  },
  {
    src: "/gallery/cars/photo_2026-02-07_20-33-59 (2).jpg",
    title: "Photo 2026 02 07 20 33 59 (2)",
    category: "Cars",
    audience: ["agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Automotive content style for car-focused creator and brand campaigns.",
  },
  {
    src: "/gallery/cars/photo_2026-03-04_14-01-55.jpg",
    title: "Photo 2026 03 04 14 01 55",
    category: "Cars",
    audience: ["agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Automotive content style for car-focused creator and brand campaigns.",
  },
  {
    src: "/gallery/cars/photo_2026-03-04_14-01-57.jpg",
    title: "Photo 2026 03 04 14 01 57",
    category: "Cars",
    audience: ["agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Automotive content style for car-focused creator and brand campaigns.",
  },
  {
    src: "/gallery/cars/photo_2026-03-04_14-01-58.jpg",
    title: "Photo 2026 03 04 14 01 58",
    category: "Cars",
    audience: ["agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Automotive content style for car-focused creator and brand campaigns.",
  },
  {
    src: "/gallery/motorcycles/1008.mp4",
    title: "1008",
    category: "Motorcycles",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "video",
    nsfw: false,
    description: "Motorcycle-focused aesthetic for rider and moto brand visuals.",
  },
  {
    src: "/gallery/motorcycles/1012.mp4",
    title: "1012",
    category: "Motorcycles",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "video",
    nsfw: false,
    description: "Motorcycle-focused aesthetic for rider and moto brand visuals.",
  },
  {
    src: "/gallery/motorcycles/kling_20251009_Image_to_Video__356_0.mp4",
    title: "Kling 20251009 Image To Video 356 0",
    category: "Motorcycles",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "video",
    nsfw: false,
    description: "Motorcycle-focused aesthetic for rider and moto brand visuals.",
  },
  {
    src: "/gallery/motorcycles/kling_20251011_Image_to_Video_The_woman__1947_0.mp4",
    title: "Kling 20251011 Image To Video The Woman 1947 0",
    category: "Motorcycles",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "video",
    nsfw: false,
    description: "Motorcycle-focused aesthetic for rider and moto brand visuals.",
  },
  {
    src: "/gallery/motorcycles/kling_20251012_Image_to_Video_the_woman__5680_0.mp4",
    title: "Kling 20251012 Image To Video The Woman 5680 0",
    category: "Motorcycles",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "video",
    nsfw: false,
    description: "Motorcycle-focused aesthetic for rider and moto brand visuals.",
  },
  {
    src: "/gallery/motorcycles/kling_20251020_Image_to_Video_The_woman__2497_0.mp4",
    title: "Kling 20251020 Image To Video The Woman 2497 0",
    category: "Motorcycles",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "video",
    nsfw: false,
    description: "Motorcycle-focused aesthetic for rider and moto brand visuals.",
  },
  {
    src: "/gallery/motorcycles/photo_2025-01-24_15-52-22.jpg",
    title: "Photo 2025 01 24 15 52 22",
    category: "Motorcycles",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Motorcycle-focused aesthetic for rider and moto brand visuals.",
  },
  {
    src: "/gallery/motorcycles/photo_2025-08-18_21-11-56.jpg",
    title: "Photo 2025 08 18 21 11 56",
    category: "Motorcycles",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Motorcycle-focused aesthetic for rider and moto brand visuals.",
  },
  {
    src: "/gallery/motorcycles/photo_2025-10-10_19-25-01.jpg",
    title: "Photo 2025 10 10 19 25 01",
    category: "Motorcycles",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Motorcycle-focused aesthetic for rider and moto brand visuals.",
  },
  {
    src: "/gallery/motorcycles/photo_2025-10-10_19-25-11.jpg",
    title: "Photo 2025 10 10 19 25 11",
    category: "Motorcycles",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Motorcycle-focused aesthetic for rider and moto brand visuals.",
  },
  {
    src: "/gallery/motorcycles/photo_2025-10-12_09-18-16.jpg",
    title: "Photo 2025 10 12 09 18 16",
    category: "Motorcycles",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Motorcycle-focused aesthetic for rider and moto brand visuals.",
  },
  {
    src: "/gallery/motorcycles/photo_2025-10-13_09-47-01.jpg",
    title: "Photo 2025 10 13 09 47 01",
    category: "Motorcycles",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Motorcycle-focused aesthetic for rider and moto brand visuals.",
  },
  {
    src: "/gallery/motorcycles/photo_2025-10-14_16-36-43.jpg",
    title: "Photo 2025 10 14 16 36 43",
    category: "Motorcycles",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Motorcycle-focused aesthetic for rider and moto brand visuals.",
  },
  {
    src: "/gallery/motorcycles/photo_2025-10-21_05-54-32.jpg",
    title: "Photo 2025 10 21 05 54 32",
    category: "Motorcycles",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Motorcycle-focused aesthetic for rider and moto brand visuals.",
  },
];

export const homeGalleryPreviewItems: GalleryItem[] = [
  galleryItems.find((item) => item.src === "/gallery/sfw/photo_2026-01-13_03-29-38 (2).jpg")!,
  galleryItems.find((item) => item.src === "/gallery/nsfw/ComfyUI_00070_.mp4")!,
  galleryItems.find((item) => item.src === "/gallery/goth/0223.mp4")!,
  galleryItems.find((item) => item.src === "/gallery/instagram/photo_2025-01-27_22-38-11 (2).jpg")!,
  galleryItems.find((item) => item.src === "/gallery/tiktok/0210 (1).mp4")!,
  galleryItems.find((item) => item.src === "/gallery/cosplay/photo_2025-08-20_16-53-34.jpg")!,
  galleryItems.find((item) => item.src === "/gallery/luxury/photo_2025-08-20_16-53-43.jpg")!,
  galleryItems.find((item) => item.src === "/gallery/selfie/photo_2025-09-22_23-49-48 (4).jpg")!,
];
