export const galleryCategories = [
  "All",
  "SFW",
  "NSFW",
  "Goth",
  "Vacation",
  "Instagram",
  "TikTok",
  "Cosplay",
  "Luxury",
  "Selfie / UGC",
  "Gym",
  "Exercise",
  "Lingerie",
  "Swimwear",
  "Lifestyle",
  "Influencer",
  "Anime",
  "Sci-Fi",
  "Cars",
  "Motorcycles",
] as const;

export type GalleryCategory = (typeof galleryCategories)[number];
export type GalleryAudience = "individual" | "agency" | "brand";
export type GalleryVertical = "adult" | "non-adult" | "general";
export type GalleryType = "image" | "video";

export type GalleryItem = {
  src: string;
  title: string;
  category: Exclude<GalleryCategory, "All">;
  audience: GalleryAudience[];
  vertical: GalleryVertical;
  type: GalleryType;
  nsfw: boolean;
  description: string;
};

export const galleryItems: GalleryItem[] = [
  {
    src: "/gallery/sfw/photo_2026-01-13_03-29-38 (2).jpg",
    title: "Result Transformation 1",
    category: "SFW",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Safe-for-work style example for broad creator and brand output.",
  },
  {
    src: "/gallery/sfw/photo_2026-01-13_03-29-38 (3).jpg",
    title: "SFW Transformation 1",
    category: "SFW",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Safe-for-work style example for broad creator and brand output.",
  },
  {
    src: "/gallery/sfw/photo_2026-01-13_03-29-38 (4).jpg",
    title: "SFW Transformation 2",
    category: "SFW",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Safe-for-work style example for broad creator and brand output.",
  },
  {
    src: "/gallery/sfw/photo_2026-01-13_03-29-38.jpg",
    title: "SFW Transformation 3",
    category: "SFW",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Safe-for-work style example for broad creator and brand output.",
  },
  {
    src: "/gallery/sfw/photo_2026-03-04_14-01-06.jpg",
    title: "SFW Transformation 4",
    category: "SFW",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Safe-for-work style example for broad creator and brand output.",
  },
  {
    src: "/gallery/nsfw/ComfyUI_00070_.mp4",
    title: "SFW Transformation 5",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "video",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/Wanimate_00004-audio.mp4",
    title: "NSFW Transformation 1",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "video",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/ai-clothes-changer-1.jpg",
    title: "NSFW Transformation 2",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/counting clothses.mp4",
    title: "NSFW Transformation 3",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "video",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-01-24_15-52-25 (2).jpg",
    title: "NSFW Transformation 4",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-01-24_15-52-26 (2).jpg",
    title: "NSFW Transformation 5",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-01-24_15-52-26.jpg",
    title: "NSFW Transformation 6",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-01-24_15-52-27 (2).jpg",
    title: "NSFW Transformation 7",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-01-27_22-38-11 (3).jpg",
    title: "NSFW Transformation 8",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-01-27_22-38-11.jpg",
    title: "NSFW Transformation 9",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-01-29_06-48-28.jpg",
    title: "NSFW Transformation 10",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-04-21_15-36-23 (2).jpg",
    title: "NSFW Transformation 11",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-04-21_15-36-23.jpg",
    title: "NSFW Transformation 12",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-04-21_15-36-25.jpg",
    title: "NSFW Transformation 13",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-06-28_09-23-45 (2).jpg",
    title: "NSFW Transformation 14",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-06-28_09-23-45.jpg",
    title: "NSFW Transformation 15",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-06-28_09-23-46.jpg",
    title: "NSFW Transformation 16",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-06-28_09-23-47.jpg",
    title: "NSFW Transformation 17",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-08-10_13-30-08 (2).jpg",
    title: "NSFW Transformation 18",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-08-10_13-30-08.jpg",
    title: "NSFW Transformation 19",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-08-10_13-30-09.jpg",
    title: "NSFW Transformation 20",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-08-15_10-38-21.jpg",
    title: "NSFW Transformation 21",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-08-16_17-35-13.jpg",
    title: "NSFW Transformation 22",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-08-17_18-01-19 (2).jpg",
    title: "NSFW Transformation 23",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-08-17_18-01-19.jpg",
    title: "NSFW Transformation 24",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-08-18_03-14-25.jpg",
    title: "NSFW Transformation 25",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-08-18_21-11-39.jpg",
    title: "NSFW Transformation 26",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-08-20_16-53-42 (2).jpg",
    title: "NSFW Transformation 27",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-08-20_16-53-45 (2).jpg",
    title: "NSFW Transformation 28",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-03_07-58-49 (2).jpg",
    title: "NSFW Transformation 29",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-03_07-58-49.jpg",
    title: "NSFW Transformation 30",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-07_22-23-02.jpg",
    title: "NSFW Transformation 31",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-07_22-25-02.jpg",
    title: "NSFW Transformation 32",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-22_23-49-48 (2).jpg",
    title: "NSFW Transformation 33",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-22_23-49-48 (5).jpg",
    title: "NSFW Transformation 34",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-22_23-49-48 (6).jpg",
    title: "NSFW Transformation 35",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-22_23-49-49 (3).jpg",
    title: "NSFW Transformation 36",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-22_23-49-49 (5).jpg",
    title: "NSFW Transformation 37",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-22_23-49-49 (6).jpg",
    title: "NSFW Transformation 38",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-22_23-49-50 (2).jpg",
    title: "NSFW Transformation 39",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-22_23-49-50 (4).jpg",
    title: "NSFW Transformation 40",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-22_23-49-51.jpg",
    title: "NSFW Transformation 41",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-30_08-29-22 (2).jpg",
    title: "NSFW Transformation 42",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-30_08-29-22.jpg",
    title: "NSFW Transformation 43",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-30_09-01-54.jpg",
    title: "NSFW Transformation 44",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-30_09-01-55 (2).jpg",
    title: "NSFW Transformation 45",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-30_09-01-56 (2).jpg",
    title: "NSFW Transformation 46",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-09-30_09-01-56.jpg",
    title: "NSFW Transformation 47",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-10-01_10-04-13.jpg",
    title: "NSFW Transformation 48",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-10-01_21-07-08.jpg",
    title: "NSFW Transformation 49",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-10-01_21-07-39 (2).jpg",
    title: "NSFW Transformation 50",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-10-01_21-07-39.jpg",
    title: "NSFW Transformation 51",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-10-01_21-07-41.jpg",
    title: "NSFW Transformation 52",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-10-01_21-07-59.jpg",
    title: "NSFW Transformation 53",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-10-01_22-02-02 (2).jpg",
    title: "NSFW Transformation 54",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-10-01_22-02-02.jpg",
    title: "NSFW Transformation 55",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-10-01_22-02-03.jpg",
    title: "NSFW Transformation 56",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-10-01_22-02-06.jpg",
    title: "NSFW Transformation 57",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-10-01_22-02-07 (2).jpg",
    title: "NSFW Transformation 58",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-10-01_22-02-07.jpg",
    title: "NSFW Transformation 59",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-10-17_17-25-31.jpg",
    title: "NSFW Transformation 60",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-01_13-38-15 (2).jpg",
    title: "NSFW Transformation 61",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-01_13-38-15.jpg",
    title: "NSFW Transformation 62",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-02_05-58-10 (2).jpg",
    title: "NSFW Transformation 63",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-02_05-58-10 (3).jpg",
    title: "NSFW Transformation 64",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-02_05-58-10 (4).jpg",
    title: "NSFW Transformation 65",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-02_05-58-10.jpg",
    title: "NSFW Transformation 66",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-02_05-58-24 (2).jpg",
    title: "NSFW Transformation 67",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-02_05-58-24 (3).jpg",
    title: "NSFW Transformation 68",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-02_05-58-24 (4).jpg",
    title: "NSFW Transformation 69",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-02_05-58-24.jpg",
    title: "NSFW Transformation 70",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-02_05-58-34 (2).jpg",
    title: "NSFW Transformation 71",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-02_05-58-46 (2).jpg",
    title: "NSFW Transformation 72",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-02_05-58-46 (5).jpg",
    title: "NSFW Transformation 73",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-05_20-23-59 (2).jpg",
    title: "NSFW Transformation 74",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-05_20-23-59.jpg",
    title: "NSFW Transformation 75",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-11_06-33-29 (2).jpg",
    title: "NSFW Transformation 76",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-11_06-33-29.jpg",
    title: "NSFW Transformation 77",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2025-11-24_11-58-31.jpg",
    title: "NSFW Transformation 78",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2026-01-03_10-03-09 (2).jpg",
    title: "NSFW Transformation 79",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2026-01-03_10-03-09.jpg",
    title: "NSFW Transformation 80",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2026-01-15_05-43-31.jpg",
    title: "NSFW Transformation 81",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2026-02-07_20-34-15 (2).jpg",
    title: "NSFW Transformation 82",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2026-02-24_15-12-52.jpg",
    title: "NSFW Transformation 83",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2026-02-24_15-18-21.jpg",
    title: "NSFW Transformation 84",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2026-03-04_14-01-40.jpg",
    title: "NSFW Transformation 85",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/nsfw/photo_2026-03-04_14-01-41.jpg",
    title: "NSFW Transformation 86",
    category: "NSFW",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: true,
    description: "Adult-oriented style example with configurable mood and presentation.",
  },
  {
    src: "/gallery/goth/0223.mp4",
    title: "NSFW Transformation 87",
    category: "Goth",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "video",
    nsfw: false,
    description: "Alternative dark aesthetic with goth styling and mood control.",
  },
  {
    src: "/gallery/goth/photo_2025-06-27_07-56-07.jpg",
    title: "Goth Transformation 1",
    category: "Goth",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Alternative dark aesthetic with goth styling and mood control.",
  },
  {
    src: "/gallery/goth/photo_2025-07-14_10-57-44.jpg",
    title: "Goth Transformation 2",
    category: "Goth",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Alternative dark aesthetic with goth styling and mood control.",
  },
  {
    src: "/gallery/goth/photo_2025-09-30_09-01-54 (2).jpg",
    title: "Goth Transformation 3",
    category: "Goth",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Alternative dark aesthetic with goth styling and mood control.",
  },
  {
    src: "/gallery/goth/photo_2025-09-30_09-01-55.jpg",
    title: "Goth Transformation 4",
    category: "Goth",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Alternative dark aesthetic with goth styling and mood control.",
  },
  {
    src: "/gallery/instagram/photo_2025-01-27_22-38-11 (2).jpg",
    title: "Goth Transformation 5",
    category: "Instagram",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Instagram-ready polished aesthetic for premium social feeds.",
  },
  {
    src: "/gallery/instagram/photo_2025-01-27_22-38-12.jpg",
    title: "Instagram Transformation 1",
    category: "Instagram",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Instagram-ready polished aesthetic for premium social feeds.",
  },
  {
    src: "/gallery/instagram/photo_2026-03-04_14-00-47.jpg",
    title: "Instagram Transformation 2",
    category: "Instagram",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Instagram-ready polished aesthetic for premium social feeds.",
  },
  {
    src: "/gallery/tiktok/0210 (1).mp4",
    title: "Instagram Transformation 3",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "video",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/0219.mp4",
    title: "TikTok Transformation 1",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "video",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/0224.mp4",
    title: "TikTok Transformation 2",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "video",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/1008(2).mp4",
    title: "TikTok Transformation 3",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "video",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/ComfyUI_00018_.mp4",
    title: "TikTok Transformation 4",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "video",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/Onlytwinvideo2.mp4",
    title: "TikTok Transformation 5",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "video",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/Wanimate_00005-audio.mp4",
    title: "TikTok Transformation 6",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "video",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/ai-clothes-changer-2.jpg",
    title: "TikTok Transformation 7",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/ai-clothes-changer-4.jpg",
    title: "TikTok Transformation 8",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/kling_20251007_Image_to_Video_the_woman__5943_0.mp4",
    title: "TikTok Transformation 9",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "video",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2025-01-27_22-38-11 (4).jpg",
    title: "TikTok Transformation 10",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2025-07-15_20-48-03.jpg",
    title: "TikTok Transformation 11",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2025-09-30_09-01-55 (3).jpg",
    title: "TikTok Transformation 12",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2025-10-02_10-40-32.jpg",
    title: "TikTok Transformation 13",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2025-10-02_10-46-33 (2).jpg",
    title: "TikTok Transformation 14",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2025-10-02_10-46-33.jpg",
    title: "TikTok Transformation 15",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2025-10-03_05-57-05 (2).jpg",
    title: "TikTok Transformation 16",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2025-10-03_05-57-05.jpg",
    title: "TikTok Transformation 17",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2025-10-26_06-51-41.jpg",
    title: "TikTok Transformation 18",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2025-11-02_05-58-34 (3).jpg",
    title: "TikTok Transformation 19",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2025-11-02_05-58-34.jpg",
    title: "TikTok Transformation 20",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2025-11-02_05-58-46 (4).jpg",
    title: "TikTok Transformation 21",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2025-11-02_05-58-46.jpg",
    title: "TikTok Transformation 22",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2025-11-17_01-15-07 (2).jpg",
    title: "TikTok Transformation 23",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2025-11-17_01-15-07.jpg",
    title: "TikTok Transformation 24",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-01-11_18-40-46.jpg",
    title: "TikTok Transformation 25",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-01-11_19-06-54.jpg",
    title: "TikTok Transformation 26",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-01-11_19-07-02.jpg",
    title: "TikTok Transformation 27",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-01-13_03-34-50 (2).jpg",
    title: "TikTok Transformation 28",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-01-13_03-34-50.jpg",
    title: "TikTok Transformation 29",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-02-07_20-32-37 (2).jpg",
    title: "TikTok Transformation 30",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-02-07_20-33-56 (3).jpg",
    title: "TikTok Transformation 31",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-02-07_20-33-56.jpg",
    title: "TikTok Transformation 32",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-02-07_20-33-57.jpg",
    title: "TikTok Transformation 33",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-02-07_20-33-59.jpg",
    title: "TikTok Transformation 34",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-02-07_20-34-07.jpg",
    title: "TikTok Transformation 35",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-02-24_15-18-16.jpg",
    title: "TikTok Transformation 36",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-02-24_15-18-17.jpg",
    title: "TikTok Transformation 37",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-02-24_15-18-20.jpg",
    title: "TikTok Transformation 38",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-00-26.jpg",
    title: "TikTok Transformation 39",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-00-28.jpg",
    title: "TikTok Transformation 40",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-00-33.jpg",
    title: "TikTok Transformation 41",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-00-35.jpg",
    title: "TikTok Transformation 42",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-00-46.jpg",
    title: "TikTok Transformation 43",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-00-56.jpg",
    title: "TikTok Transformation 44",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-01-01 (2).jpg",
    title: "TikTok Transformation 45",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-01-01.jpg",
    title: "TikTok Transformation 46",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-01-09.jpg",
    title: "TikTok Transformation 47",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-01-20 (2).jpg",
    title: "TikTok Transformation 48",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-01-20.jpg",
    title: "TikTok Transformation 49",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-01-22.jpg",
    title: "TikTok Transformation 50",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-01-38.jpg",
    title: "TikTok Transformation 51",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-01-44.jpg",
    title: "TikTok Transformation 52",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-01-46.jpg",
    title: "TikTok Transformation 53",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-01-49.jpg",
    title: "TikTok Transformation 54",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-01-53.jpg",
    title: "TikTok Transformation 55",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-02-02 (2).jpg",
    title: "TikTok Transformation 56",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-02-02.jpg",
    title: "TikTok Transformation 57",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/tiktok/photo_2026-03-04_14-02-04.jpg",
    title: "TikTok Transformation 58",
    category: "TikTok",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Short-form social style for vertical content and fast engagement.",
  },
  {
    src: "/gallery/cosplay/photo_2025-08-20_16-53-34.jpg",
    title: "TikTok Transformation 59",
    category: "Cosplay",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Character and cosplay-focused generation with niche styling.",
  },
  {
    src: "/gallery/cosplay/photo_2025-08-20_16-53-44.jpg",
    title: "Cosplay Transformation 1",
    category: "Cosplay",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Character and cosplay-focused generation with niche styling.",
  },
  {
    src: "/gallery/luxury/photo_2025-08-20_16-53-43.jpg",
    title: "Cosplay Transformation 2",
    category: "Luxury",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Luxury and glam visual direction with premium editorial polish.",
  },
  {
    src: "/gallery/luxury/photo_2025-08-22_07-22-12 (2).jpg",
    title: "Luxury Transformation 1",
    category: "Luxury",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Luxury and glam visual direction with premium editorial polish.",
  },
  {
    src: "/gallery/luxury/photo_2026-02-07_20-34-15.jpg",
    title: "Luxury Transformation 2",
    category: "Luxury",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Luxury and glam visual direction with premium editorial polish.",
  },
  {
    src: "/gallery/selfie/photo_2025-09-22_23-49-48 (4).jpg",
    title: "Luxury Transformation 3",
    category: "Selfie / UGC",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "UGC-style selfie output designed for natural platform realism.",
  },
  {
    src: "/gallery/selfie/photo_2025-09-22_23-49-48 (7).jpg",
    title: "Selfie / UGC Transformation 1",
    category: "Selfie / UGC",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "UGC-style selfie output designed for natural platform realism.",
  },
  {
    src: "/gallery/selfie/photo_2025-09-22_23-49-48 (9).jpg",
    title: "Selfie / UGC Transformation 2",
    category: "Selfie / UGC",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "UGC-style selfie output designed for natural platform realism.",
  },
  {
    src: "/gallery/selfie/photo_2025-09-22_23-49-48.jpg",
    title: "Selfie / UGC Transformation 3",
    category: "Selfie / UGC",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "UGC-style selfie output designed for natural platform realism.",
  },
  {
    src: "/gallery/selfie/photo_2025-10-01_21-07-08 (3).jpg",
    title: "Selfie / UGC Transformation 4",
    category: "Selfie / UGC",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "UGC-style selfie output designed for natural platform realism.",
  },
  {
    src: "/gallery/selfie/photo_2026-03-04_14-01-52.jpg",
    title: "Selfie / UGC Transformation 5",
    category: "Selfie / UGC",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "UGC-style selfie output designed for natural platform realism.",
  },
  {
    src: "/gallery/gym/photo_2026-03-04_14-00-39.jpg",
    title: "Selfie / UGC Transformation 6",
    category: "Gym",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Fitness and gym style generation for workout and training niches.",
  },
  {
    src: "/gallery/exercise/photo_2025-01-29_06-48-24.jpg",
    title: "Gym Transformation 1",
    category: "Exercise",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Exercise and activewear-focused visuals with motion-driven styling.",
  },
  {
    src: "/gallery/exercise/photo_2026-02-07_20-32-37.jpg",
    title: "Exercise Transformation 1",
    category: "Exercise",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Exercise and activewear-focused visuals with motion-driven styling.",
  },
  {
    src: "/gallery/exercise/photo_2026-02-24_15-18-23.jpg",
    title: "Exercise Transformation 2",
    category: "Exercise",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Exercise and activewear-focused visuals with motion-driven styling.",
  },
  {
    src: "/gallery/exercise/photo_2026-02-24_15-18-26.jpg",
    title: "Exercise Transformation 3",
    category: "Exercise",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Exercise and activewear-focused visuals with motion-driven styling.",
  },
  {
    src: "/gallery/exercise/photo_2026-03-04_14-00-43.jpg",
    title: "Exercise Transformation 4",
    category: "Exercise",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Exercise and activewear-focused visuals with motion-driven styling.",
  },
  {
    src: "/gallery/exercise/photo_2026-03-04_14-00-55.jpg",
    title: "Exercise Transformation 5",
    category: "Exercise",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Exercise and activewear-focused visuals with motion-driven styling.",
  },
  {
    src: "/gallery/exercise/photo_2026-03-04_14-00-57.jpg",
    title: "Exercise Transformation 6",
    category: "Exercise",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Exercise and activewear-focused visuals with motion-driven styling.",
  },
  {
    src: "/gallery/exercise/photo_2026-03-04_14-00-58.jpg",
    title: "Exercise Transformation 7",
    category: "Exercise",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Exercise and activewear-focused visuals with motion-driven styling.",
  },
  {
    src: "/gallery/lingerie/photo_2025-01-24_15-52-24.jpg",
    title: "Exercise Transformation 8",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2025-01-24_15-52-25.jpg",
    title: "Lingerie Transformation 1",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2025-01-24_15-52-27.jpg",
    title: "Lingerie Transformation 2",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2025-01-27_22-38-10.jpg",
    title: "Lingerie Transformation 3",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2025-01-27_22-38-12 (2).jpg",
    title: "Lingerie Transformation 4",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2025-08-18_21-11-12 (2).jpg",
    title: "Lingerie Transformation 5",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2025-08-18_21-11-12.jpg",
    title: "Lingerie Transformation 6",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2025-08-18_21-12-03 (2).jpg",
    title: "Lingerie Transformation 7",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2025-09-04_20-22-16.jpg",
    title: "Lingerie Transformation 8",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2025-09-22_23-49-49 (2).jpg",
    title: "Lingerie Transformation 9",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2025-09-22_23-49-49 (4).jpg",
    title: "Lingerie Transformation 10",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2025-09-22_23-49-49.jpg",
    title: "Lingerie Transformation 11",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2025-09-22_23-49-50 (3).jpg",
    title: "Lingerie Transformation 12",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2025-10-01_21-07-08 (2).jpg",
    title: "Lingerie Transformation 13",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2026-02-07_20-33-55 (2).jpg",
    title: "Lingerie Transformation 14",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2026-02-07_20-34-00.jpg",
    title: "Lingerie Transformation 15",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2026-02-24_15-12-53.jpg",
    title: "Lingerie Transformation 16",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2026-03-04_14-01-22 (2).jpg",
    title: "Lingerie Transformation 17",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2026-03-04_14-01-24.jpg",
    title: "Lingerie Transformation 18",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2026-03-04_14-01-25.jpg",
    title: "Lingerie Transformation 19",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2026-03-04_14-01-27 (2).jpg",
    title: "Lingerie Transformation 20",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2026-03-04_14-01-27.jpg",
    title: "Lingerie Transformation 21",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2026-03-04_14-02-00.jpg",
    title: "Lingerie Transformation 22",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/lingerie/photo_2026-03-04_14-02-01.jpg",
    title: "Lingerie Transformation 23",
    category: "Lingerie",
    audience: ["individual", "agency"],
    vertical: "adult",
    type: "image",
    nsfw: false,
    description: "Lingerie style direction with premium studio and lifestyle framing.",
  },
  {
    src: "/gallery/swimwear/photo_2025-07-23_17-23-44.jpg",
    title: "Lingerie Transformation 24",
    category: "Swimwear",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Swimwear and beach-oriented visuals across social and promo use.",
  },
  {
    src: "/gallery/swimwear/photo_2025-11-02_05-58-46 (3).jpg",
    title: "Swimwear Transformation 1",
    category: "Swimwear",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Swimwear and beach-oriented visuals across social and promo use.",
  },
  {
    src: "/gallery/swimwear/photo_2026-02-07_20-34-05.jpg",
    title: "Swimwear Transformation 2",
    category: "Swimwear",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Swimwear and beach-oriented visuals across social and promo use.",
  },
  {
    src: "/gallery/swimwear/photo_2026-02-07_20-34-06.jpg",
    title: "Swimwear Transformation 3",
    category: "Swimwear",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Swimwear and beach-oriented visuals across social and promo use.",
  },
  {
    src: "/gallery/lifestyle/photo_2025-04-21_15-36-24.jpg",
    title: "Swimwear Transformation 4",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2025-07-03_16-54-23.jpg",
    title: "Lifestyle Transformation 1",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2025-08-18_21-11-13.jpg",
    title: "Lifestyle Transformation 2",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2025-08-18_21-12-03.jpg",
    title: "Lifestyle Transformation 3",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2025-08-22_07-22-12.jpg",
    title: "Lifestyle Transformation 4",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2025-09-22_23-49-48 (3).jpg",
    title: "Lifestyle Transformation 5",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2025-09-22_23-49-48 (8).jpg",
    title: "Lifestyle Transformation 6",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2025-09-22_23-49-50 (5).jpg",
    title: "Lifestyle Transformation 7",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2025-09-22_23-49-50.jpg",
    title: "Lifestyle Transformation 8",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2025-09-27_04-36-10 (4).jpg",
    title: "Lifestyle Transformation 9",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2025-09-27_04-36-10.jpg",
    title: "Lifestyle Transformation 10",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2025-10-01_10-04-13 (2).jpg",
    title: "Lifestyle Transformation 11",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2025-11-05_20-26-34 (2).jpg",
    title: "Lifestyle Transformation 12",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2025-11-05_20-26-34.jpg",
    title: "Lifestyle Transformation 13",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2026-01-11_18-46-57.jpg",
    title: "Lifestyle Transformation 14",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2026-01-13_03-42-37 (2).jpg",
    title: "Lifestyle Transformation 15",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2026-01-13_03-42-37.jpg",
    title: "Lifestyle Transformation 16",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2026-02-07_20-32-38.jpg",
    title: "Lifestyle Transformation 17",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2026-02-07_20-33-56 (2).jpg",
    title: "Lifestyle Transformation 18",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2026-02-07_20-34-05 (2).jpg",
    title: "Lifestyle Transformation 19",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2026-02-07_20-34-07 (2).jpg",
    title: "Lifestyle Transformation 20",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2026-02-07_20-34-07 (3).jpg",
    title: "Lifestyle Transformation 21",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2026-02-24_15-18-27.jpg",
    title: "Lifestyle Transformation 22",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2026-02-24_15-18-28.jpg",
    title: "Lifestyle Transformation 23",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2026-02-24_15-18-30.jpg",
    title: "Lifestyle Transformation 24",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2026-03-04_14-00-34.jpg",
    title: "Lifestyle Transformation 25",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2026-03-04_14-00-36.jpg",
    title: "Lifestyle Transformation 26",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2026-03-04_14-00-49.jpg",
    title: "Lifestyle Transformation 27",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2026-03-04_14-01-15.jpg",
    title: "Lifestyle Transformation 28",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2026-03-04_14-01-34.jpg",
    title: "Lifestyle Transformation 29",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/lifestyle/photo_2026-03-04_14-01-42.jpg",
    title: "Lifestyle Transformation 30",
    category: "Lifestyle",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Everyday lifestyle visual style adaptable to multiple personas.",
  },
  {
    src: "/gallery/influencer/ai-clothes-changer-3.jpg",
    title: "Lifestyle Transformation 31",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/influencer/photo_2025-08-20_16-53-34 (2).jpg",
    title: "Influencer Transformation 1",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/influencer/photo_2025-08-20_16-53-43 (2).jpg",
    title: "Influencer Transformation 2",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/influencer/photo_2025-08-20_16-53-45.jpg",
    title: "Influencer Transformation 3",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/influencer/photo_2025-09-27_04-36-10 (3).jpg",
    title: "Influencer Transformation 4",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/influencer/photo_2025-09-27_04-36-11.jpg",
    title: "Influencer Transformation 5",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/influencer/photo_2025-10-04_10-49-36.jpg",
    title: "Influencer Transformation 6",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/influencer/photo_2025-10-04_18-18-22 (2).jpg",
    title: "Influencer Transformation 7",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/influencer/photo_2025-10-04_18-18-22.jpg",
    title: "Influencer Transformation 8",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/influencer/photo_2025-10-04_18-22-52.jpg",
    title: "Influencer Transformation 9",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/influencer/photo_2025-11-17_21-26-13 (2).jpg",
    title: "Influencer Transformation 10",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/influencer/photo_2026-02-07_20-33-55.jpg",
    title: "Influencer Transformation 11",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/influencer/photo_2026-02-07_20-33-58 (2).jpg",
    title: "Influencer Transformation 12",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/influencer/photo_2026-02-07_20-33-58.jpg",
    title: "Influencer Transformation 13",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/influencer/photo_2026-02-07_20-34-01.jpg",
    title: "Influencer Transformation 14",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/influencer/photo_2026-03-04_14-00-50.jpg",
    title: "Influencer Transformation 15",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/influencer/photo_2026-03-04_14-01-36.jpg",
    title: "Influencer Transformation 16",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/influencer/photo_2026-03-04_14-01-47.jpg",
    title: "Influencer Transformation 17",
    category: "Influencer",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Influencer persona output for creator-led content programs.",
  },
  {
    src: "/gallery/scifi/photo_2025-08-20_16-53-42.jpg",
    title: "Influencer Transformation 18",
    category: "Sci-Fi",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Sci-fi and futuristic looks with cinematic lighting and scenes.",
  },
  {
    src: "/gallery/scifi/photo_2025-11-17_21-26-13.jpg",
    title: "Sci-Fi Transformation 1",
    category: "Sci-Fi",
    audience: ["individual", "agency", "brand"],
    vertical: "general",
    type: "image",
    nsfw: false,
    description: "Sci-fi and futuristic looks with cinematic lighting and scenes.",
  },
  {
    src: "/gallery/cars/photo_2025-09-27_04-36-10 (2).jpg",
    title: "Sci-Fi Transformation 2",
    category: "Cars",
    audience: ["agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Automotive content style for car-focused creator and brand campaigns.",
  },
  {
    src: "/gallery/cars/photo_2025-09-27_04-36-10 (5).jpg",
    title: "Cars Transformation 1",
    category: "Cars",
    audience: ["agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Automotive content style for car-focused creator and brand campaigns.",
  },
  {
    src: "/gallery/cars/photo_2026-02-07_20-33-59 (2).jpg",
    title: "Cars Transformation 2",
    category: "Cars",
    audience: ["agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Automotive content style for car-focused creator and brand campaigns.",
  },
  {
    src: "/gallery/cars/photo_2026-03-04_14-01-55.jpg",
    title: "Cars Transformation 3",
    category: "Cars",
    audience: ["agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Automotive content style for car-focused creator and brand campaigns.",
  },
  {
    src: "/gallery/cars/photo_2026-03-04_14-01-57.jpg",
    title: "Cars Transformation 4",
    category: "Cars",
    audience: ["agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Automotive content style for car-focused creator and brand campaigns.",
  },
  {
    src: "/gallery/cars/photo_2026-03-04_14-01-58.jpg",
    title: "Cars Transformation 5",
    category: "Cars",
    audience: ["agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Automotive content style for car-focused creator and brand campaigns.",
  },
  {
    src: "/gallery/motorcycles/1008.mp4",
    title: "Cars Transformation 6",
    category: "Motorcycles",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "video",
    nsfw: false,
    description: "Motorcycle-focused aesthetic for rider and moto brand visuals.",
  },
  {
    src: "/gallery/motorcycles/1012.mp4",
    title: "Motorcycles Transformation 1",
    category: "Motorcycles",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "video",
    nsfw: false,
    description: "Motorcycle-focused aesthetic for rider and moto brand visuals.",
  },
  {
    src: "/gallery/motorcycles/kling_20251009_Image_to_Video__356_0.mp4",
    title: "Motorcycles Transformation 2",
    category: "Motorcycles",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "video",
    nsfw: false,
    description: "Motorcycle-focused aesthetic for rider and moto brand visuals.",
  },
  {
    src: "/gallery/motorcycles/kling_20251011_Image_to_Video_The_woman__1947_0.mp4",
    title: "Motorcycles Transformation 3",
    category: "Motorcycles",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "video",
    nsfw: false,
    description: "Motorcycle-focused aesthetic for rider and moto brand visuals.",
  },
  {
    src: "/gallery/motorcycles/kling_20251012_Image_to_Video_the_woman__5680_0.mp4",
    title: "Motorcycles Transformation 4",
    category: "Motorcycles",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "video",
    nsfw: false,
    description: "Motorcycle-focused aesthetic for rider and moto brand visuals.",
  },
  {
    src: "/gallery/motorcycles/kling_20251020_Image_to_Video_The_woman__2497_0.mp4",
    title: "Motorcycles Transformation 5",
    category: "Motorcycles",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "video",
    nsfw: false,
    description: "Motorcycle-focused aesthetic for rider and moto brand visuals.",
  },
  {
    src: "/gallery/motorcycles/photo_2025-01-24_15-52-22.jpg",
    title: "Motorcycles Transformation 6",
    category: "Motorcycles",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Motorcycle-focused aesthetic for rider and moto brand visuals.",
  },
  {
    src: "/gallery/motorcycles/photo_2025-08-18_21-11-56.jpg",
    title: "Motorcycles Transformation 7",
    category: "Motorcycles",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Motorcycle-focused aesthetic for rider and moto brand visuals.",
  },
  {
    src: "/gallery/motorcycles/photo_2025-10-10_19-25-01.jpg",
    title: "Motorcycles Transformation 8",
    category: "Motorcycles",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Motorcycle-focused aesthetic for rider and moto brand visuals.",
  },
  {
    src: "/gallery/motorcycles/photo_2025-10-10_19-25-11.jpg",
    title: "Motorcycles Transformation 9",
    category: "Motorcycles",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Motorcycle-focused aesthetic for rider and moto brand visuals.",
  },
  {
    src: "/gallery/motorcycles/photo_2025-10-12_09-18-16.jpg",
    title: "Motorcycles Transformation 10",
    category: "Motorcycles",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Motorcycle-focused aesthetic for rider and moto brand visuals.",
  },
  {
    src: "/gallery/motorcycles/photo_2025-10-13_09-47-01.jpg",
    title: "Motorcycles Transformation 11",
    category: "Motorcycles",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Motorcycle-focused aesthetic for rider and moto brand visuals.",
  },
  {
    src: "/gallery/motorcycles/photo_2025-10-14_16-36-43.jpg",
    title: "Motorcycles Transformation 12",
    category: "Motorcycles",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Motorcycle-focused aesthetic for rider and moto brand visuals.",
  },
  {
    src: "/gallery/motorcycles/photo_2025-10-21_05-54-32.jpg",
    title: "Motorcycles Transformation 13",
    category: "Motorcycles",
    audience: ["individual", "agency", "brand"],
    vertical: "non-adult",
    type: "image",
    nsfw: false,
    description: "Motorcycle-focused aesthetic for rider and moto brand visuals.",
  },
];

export const homeGalleryPreviewItems: GalleryItem[] = [
  galleryItems.find((item) => item.src === "/gallery/sfw/photo_2026-01-13_03-29-38 (2).jpg")!,
  galleryItems.find((item) => item.src === "/gallery/nsfw/ComfyUI_00070_.mp4")!,
  galleryItems.find((item) => item.src === "/gallery/goth/0223.mp4")!,
  galleryItems.find((item) => item.src === "/gallery/instagram/photo_2025-01-27_22-38-11 (2).jpg")!,
  galleryItems.find((item) => item.src === "/gallery/tiktok/0210 (1).mp4")!,
  galleryItems.find((item) => item.src === "/gallery/cosplay/photo_2025-08-20_16-53-34.jpg")!,
  galleryItems.find((item) => item.src === "/gallery/luxury/photo_2025-08-20_16-53-43.jpg")!,
  galleryItems.find((item) => item.src === "/gallery/selfie/photo_2025-09-22_23-49-48 (4).jpg")!,
];
